### ISSUE TITLE
NLP DC

### ISSUE THREAD

**Issue by SamHodges** [SamHodges/DC_OPF#2]
Currently working on getting it up and running, but will put some updates here

**Comment by SamHodges** [comment]
Traceback (most recent call last):
  File "c:\Users\samho\Desktop\PhD\DC OPF\runfile.py", line 174, in <module>
    newOPF = OPF(opf_type_ac="nonlinear", opf_type_dc="nlp", link_type="vsc", \
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\samho\Desktop\PhD\DC OPF\runfile.py", line 32, in __init__
    self.initialise_models()
  File "c:\Users\samho\Desktop\PhD\DC OPF\runfile.py", line 80, in initialise_models
    self.instance = self.model.create_instance(self.datfile)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\core\base\PyomoModel.py", line 731, in create_instance
    instance.load(data, namespaces=_namespaces, profile_memory=profile_memory)
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\core\base\PyomoModel.py", line 760, in load
    dp = DataPortal(filename=arg, model=self)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\DataPortal.py", line 69, in __init__
    self.load()
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\DataPortal.py", line 166, in load
    status = self._data_manager.process(self._model, self._data, self._default)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\plugins\datacommands.py", line 61, in process
    _process_include(['include', self.filename], model, data, default, self.options)
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\process_data.py", line 670, in _process_include
    _process_data(cmd, _model, _data[scenario], _default, Filename, Lineno)
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\process_data.py", line 1049, in _process_data
    _process_param(
  File "C:\Users\samho\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyomo\dataportal\process_data.py", line 322, in _process_param
    if cmd[0] == "(tr)":
       ~~~^^^
IndexError: list index out of range

**Comment by SamHodges** [comment]
looks like it was datfile with the DC transofrmers
